services:
  db:
      image: postgres
      volumes:
        - ./data/db:/var/lib/postgresql/data
      env_file: .env-vars
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
      shm_size: 2gb
      mem_limit: 2g
      mem_reservation: 512m
      cpus: 2
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"
      expose:
        - 5432
  app:
    build: .
    image: zeal-python
    env_file: .env-vars
    depends_on:
      db:
        condition: service_healthy
  